### ISSUE TITLE
Create Cloudflare Worker

### ISSUE THREAD

**Issue by earth2travis** [onchain-warfare/mint#2]
Create `warframes-mint` Cloudflare Worker

`wrangler.toml`

```toml
name = "warframes-mint"
main = "worker.js"
compatibility_date = "2023-08-23"
```

```bash
pnpm wrangler:deploy
```

https://warframes-mint.earth2travis.workers.dev

https://warpcast.com/~/developers/frames?url=https://warframes-mint.earth2travis.workers.dev
